### ISSUE TITLE
Unable to get the metrics value

### ISSUE THREAD

**Issue by lueliu** [moira-alert/cache#14]
I try to use Moira,but I can not monit my metrics value by Moira.
there is nodata in Moira web. Can I find the metrics value in moira-cache ?
I'm not sure whether the carbon-c-relay has to transfer the data.

Do you have any other way ?

my carbon-c-relay config file:

cluster output file
  /dev/stdout;
cluster moira
forward
    moira-cache:2003;

cluster graphite
   carbon_ch
    graphite:2003;

match *
  send to
    moira 
    graphite;

**Comment by AlexAkulov** [comment]
You can view incoming metrics via `redis-cli monitor | grep ZADD | grep moira-metric-data`

**Comment by lueliu** [comment]
thx . I can not view metrics by redis-cli tool.  
I will use other ways to monitor, then I close it.
