### ISSUE TITLE
Panic on reload

### ISSUE THREAD

**Issue by gmlexx** [moira-alert/cache#4]
апр 12 00:26:16 vm-moira moira-cache[6466]: panic: runtime error: invalid memory address or nil pointer dereference
апр 12 00:26:16 vm-moira moira-cache[6466]: [signal 0xb code=0x1 addr=0x0 pc=0x51ad90]
апр 12 00:26:16 vm-moira moira-cache[6466]: goroutine 26 [running]:
апр 12 00:26:16 vm-moira moira-cache[6466]: github.com/moira-alert/cache/filter.findPart(0xc8200c9100, 0x3, 0x39, 0xc820142c20, 0x1, 0x1, 0x0, 0x0, 0x0, 0x533e23)
апр 12 00:26:16 vm-moira moira-cache[6466]: /opt/TeamCity/buildAgent/work/8f0b3fe99b08b4df/gocode/src/github.com/moira-alert/cache/filter/pattern.go:151 +0x450
апр 12 00:26:16 vm-moira moira-cache[6466]: github.com/moira-alert/cache/filter.(*PatternStorage).MatchPattern(0xc8200c00a8, 0xc8200c9100, 0x27, 0x39, 0x0, 0x0, 0x0)
апр 12 00:26:16 vm-moira moira-cache[6466]: /opt/TeamCity/buildAgent/work/8f0b3fe99b08b4df/gocode/src/github.com/moira-alert/cache/filter/pattern.go:124 +0x1c2
апр 12 00:26:16 vm-moira moira-cache[6466]: github.com/moira-alert/cache/filter.(*PatternStorage).ProcessIncomingMetric(0xc8200c00a8, 0xc8200c9100, 0x38, 0x39, 0x0)
апр 12 00:26:16 vm-moira moira-cache[6466]: /opt/TeamCity/buildAgent/work/8f0b3fe99b08b4df/gocode/src/github.com/moira-alert/cache/filter/metric.go:98 +0x7d0
апр 12 00:26:16 vm-moira moira-cache[6466]: main.handleConnection.func1(0xc820188000, 0xc8200c9100, 0x39, 0x39, 0xc82017a000)
апр 12 00:26:16 vm-moira moira-cache[6466]: /opt/TeamCity/buildAgent/work/8f0b3fe99b08b4df/gocode/src/github.com/moira-alert/cache/main.go:198 +0x6c
апр 12 00:26:16 vm-moira moira-cache[6466]: created by main.handleConnection
апр 12 00:26:16 vm-moira moira-cache[6466]: /opt/TeamCity/buildAgent/work/8f0b3fe99b08b4df/gocode/src/github.com/moira-alert/cache/main.go:201 +0x300

**Comment by beevee** [comment]
I think we should remove reloading feature entirely. It's useless, because there is always only one connection to Moira (from carbon-c-relay), and the relay can handle reconnection gracefully.

**Comment by gmlexx** [comment]
Carbon-c-relay isn't a part of moira by design and may be this bug is not related to reload mechanics at all and also take place just during stop.
Let's investigate this panic firstly.
