### ISSUE TITLE
crash because of no /etc/moira/cache/storage-schemas.conf

### ISSUE THREAD

**Issue by blysik** [moira-alert/cache#9]
OracleEnterpriseLinux 7, via RPM
```
pid:15839 13:40:05.657611 main.go:76: error open retentions file /var/run/moira-cache.pid: open /etc/moira/cache/storage-schemas.conf: no such file or directory
```

The docs make no mention of what should be in this file.

**Comment by blysik** [comment]
I figured out what needed to be present in /etc/moira/cache/storage-schemas.conf by looking at the vagrant dev repo.

I think this file should be laid down as part of the moira-cache RPM?

**Comment by gmlexx** [comment]
Hi, added a link about storage-schemas to doc.
Moira usually used in conjunction with graphite and uses the same storage-schemas as for graphite.

**Comment by gmlexx** [comment]
#10

**Comment by blysik** [comment]
Does this mean I should copy in place the same storage-schemas.conf that I use with graphite?  Moira and my graphite cluster are on separate machines in my setup.

**Comment by AlexAkulov** [comment]
Yes, `starage-shemas.conf` must be equal for graphite and moira.

**Comment by gmlexx** [comment]
Can we close this issue?

**Comment by blysik** [comment]
Thanks for the clarification.  Closing.
